export const TABLES_CATALOG = {
  "_acordos": {
    "table": "_acordos",
    "columns": [
      "ID DO ACORDO",
      "CNPJ DO SANCIONADO",
      "RAZÃO SOCIAL – CADASTRO RECEITA",
      "NOME FANTASIA – CADASTRO RECEITA",
      "DATA DE INÍCIO DO ACORDO",
      "DATA DE FIM DO ACORDO",
      "SITUAÇÃO DO ACORDO DE LENIÊNICA",
      "DATA DA INFORMAÇÃO",
      "NÚMERO DO PROCESSO",
      "TERMOS DO ACORDO",
      "ÓRGÃO SANCIONADOR",
      "EFEITO DO ACORDO DE LENIENCIA",
      "COMPLEMENTO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_origem",
      "_audit_linha_csv",
      "_audit_arquivo_csv_origem",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CNPJ DO SANCIONADO",
      "RAZÃO SOCIAL – CADASTRO RECEITA",
      "NOME FANTASIA – CADASTRO RECEITA",
      "NÚMERO DO PROCESSO",
      "ÓRGÃO SANCIONADOR"
    ],
    "dateColumns": [
      "DATA DE INÍCIO DO ACORDO",
      "DATA DE FIM DO ACORDO",
      "DATA DA INFORMAÇÃO"
    ],
    "valueColumns": [],
    "hasAudit": true
  },
  "_apoiamentoemendasparlamentares": {
    "table": "_apoiamentoemendasparlamentares",
    "columns": [
      "Código Apoiador",
      "Apoiador",
      "Data do Apoio",
      "Data Retirada do Apoio",
      "Empenho",
      "Data última movimentação Empenho",
      "Código favorecido",
      "Favorecido",
      "Tipo Favorecido",
      "UF Favorecido",
      "Município Favorecido",
      "Código da Emenda",
      "Tipo de Emenda",
      "Ano da Emenda",
      "Código do Autor da Emenda",
      "Nome do Autor da Emenda",
      "Número da emenda",
      "Localidade de aplicação do recurso",
      "Código UG",
      "UG",
      "Código Unidade Orçamentária",
      "Unidade Orçamentária",
      "Código Órgão SIAFI",
      "Órgão",
      "Código Órgão Superior SIAFI",
      "Órgão Superior",
      "Código Ação",
      "Ação",
      "Valor Empenhado",
      "Valor Cancelado",
      "Valor Pago"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_origem",
      "_audit_linha_csv",
      "_audit_arquivo_csv_origem",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "Código favorecido",
      "Favorecido",
      "Tipo Favorecido",
      "UF Favorecido",
      "Município Favorecido",
      "Nome do Autor da Emenda",
      "Código Órgão SIAFI",
      "Órgão",
      "Código Órgão Superior SIAFI",
      "Órgão Superior"
    ],
    "dateColumns": [
      "Data do Apoio",
      "Data Retirada do Apoio",
      "Data última movimentação Empenho",
      "Ano da Emenda"
    ],
    "valueColumns": [
      "Valor Empenhado",
      "Valor Cancelado",
      "Valor Pago"
    ],
    "hasAudit": true
  },
  "_auxiliobrasil": {
    "table": "_auxiliobrasil",
    "columns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_origem",
      "_audit_linha_csv",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv_1",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA"
    ],
    "valueColumns": [
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_auxilioemergencial": {
    "table": "_auxilioemergencial",
    "columns": [
      "MÊS DISPONIBILIZAÇÃO",
      "UF",
      "CÓDIGO MUNICÍPIO IBGE",
      "NOME MUNICÍPIO",
      "NIS BENEFICIÁRIO",
      "CPF BENEFICIÁRIO",
      "NOME BENEFICIÁRIO",
      "NIS RESPONSÁVEL",
      "CPF RESPONSÁVEL",
      "NOME RESPONSÁVEL",
      "ENQUADRAMENTO",
      "PARCELA",
      "OBSERVAÇÃO",
      "VALOR BENEFÍCIO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_origem",
      "_audit_linha_csv",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv_1",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO IBGE",
      "NOME MUNICÍPIO",
      "CPF BENEFICIÁRIO",
      "NOME BENEFICIÁRIO",
      "CPF RESPONSÁVEL",
      "NOME RESPONSÁVEL"
    ],
    "dateColumns": [
      "MÊS DISPONIBILIZAÇÃO"
    ],
    "valueColumns": [
      "VALOR BENEFÍCIO"
    ],
    "hasAudit": true
  },
  "_auxilioreconstrucao": {
    "table": "_auxilioreconstrucao",
    "columns": [
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO",
      "QUANTIDADE DE PESSOAS NA FAMÍLIA",
      "DATA EFETIVAÇÃO PARCELA",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_origem",
      "_audit_linha_csv",
      "_audit_arquivo_csv_origem",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "MÊS REFERÊNCIA",
      "DATA EFETIVAÇÃO PARCELA"
    ],
    "valueColumns": [
      "QUANTIDADE DE PESSOAS NA FAMÍLIA",
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_bolsafamilia_pagamentos": {
    "table": "_bolsafamilia_pagamentos",
    "columns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_origem",
      "_audit_linha_csv",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv_1",
      "_audit_row_hash",
      "_audit_periodicidade_atualizacao_gov",
      "_audit_data_disponibilizacao_chat"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA"
    ],
    "valueColumns": [
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_bolsafamilia_saques": {
    "table": "_bolsafamilia_saques",
    "columns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO",
      "DATA SAQUE",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA",
      "DATA SAQUE"
    ],
    "valueColumns": [
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_bpc": {
    "table": "_bpc",
    "columns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "NIS BENEFICIÁRIO",
      "CPF BENEFICIÁRIO",
      "NOME BENEFICIÁRIO",
      "NIS REPRESENTANTE LEGAL",
      "CPF REPRESENTANTE LEGAL",
      "NOME REPRESENTANTE LEGAL",
      "NÚMERO BENEFÍCIO",
      "BENEFÍCIO CONCEDIDO JUDICIALMENTE",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF BENEFICIÁRIO",
      "NOME BENEFICIÁRIO",
      "CPF REPRESENTANTE LEGAL",
      "NOME REPRESENTANTE LEGAL"
    ],
    "dateColumns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA"
    ],
    "valueColumns": [
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_ceaf": {
    "table": "_ceaf",
    "columns": [
      "CADASTRO",
      "CÓDIGO DA SANÇÃO",
      "TIPO DE PESSOA",
      "CPF OU CNPJ DO SANCIONADO",
      "NOME DO SANCIONADO",
      "CATEGORIA DA SANÇÃO",
      "NÚMERO DO DOCUMENTO",
      "NÚMERO DO PROCESSO",
      "DATA INÍCIO SANÇÃO",
      "DATA FINAL SANÇÃO",
      "DATA PUBLICAÇÃO",
      "PUBLICAÇÃO",
      "DETALHAMENTO  DO MEIO DE PUBLICAÇÃO",
      "DATA DO TRÂNSITO EM JULGADO",
      "ABRAGÊNCIA DA SANÇÃO",
      "CARGO EFETIVO",
      "FUNÇÃO OU CARGO DE CONFIANÇA",
      "ÓRGÃO DE LOTAÇÃO",
      "ÓRGÃO SANCIONADOR",
      "UF ÓRGÃO SANCIONADOR",
      "ESFERA ÓRGÃO SANCIONADOR",
      "FUNDAMENTAÇÃO LEGAL",
      "DATA ORIGEM INFORMAÇÃO",
      "ORIGEM INFORMAÇÕES",
      "OBSERVAÇÕES"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CPF OU CNPJ DO SANCIONADO",
      "NOME DO SANCIONADO",
      "NÚMERO DO DOCUMENTO",
      "NÚMERO DO PROCESSO",
      "CARGO EFETIVO",
      "FUNÇÃO OU CARGO DE CONFIANÇA",
      "ÓRGÃO DE LOTAÇÃO",
      "ÓRGÃO SANCIONADOR",
      "UF ÓRGÃO SANCIONADOR",
      "ESFERA ÓRGÃO SANCIONADOR"
    ],
    "dateColumns": [
      "DATA INÍCIO SANÇÃO",
      "DATA FINAL SANÇÃO",
      "DATA PUBLICAÇÃO",
      "DATA DO TRÂNSITO EM JULGADO",
      "DATA ORIGEM INFORMAÇÃO"
    ],
    "valueColumns": [],
    "hasAudit": true
  },
  "_ceis": {
    "table": "_ceis",
    "columns": [
      "CADASTRO",
      "CÓDIGO DA SANÇÃO",
      "TIPO DE PESSOA",
      "CPF OU CNPJ DO SANCIONADO",
      "NOME DO SANCIONADO",
      "NOME INFORMADO PELO ÓRGÃO SANCIONADOR",
      "RAZÃO SOCIAL - CADASTRO RECEITA",
      "NOME FANTASIA - CADASTRO RECEITA",
      "NÚMERO DO PROCESSO",
      "CATEGORIA DA SANÇÃO",
      "DATA INÍCIO SANÇÃO",
      "DATA FINAL SANÇÃO",
      "DATA PUBLICAÇÃO",
      "PUBLICAÇÃO",
      "DETALHAMENTO DO MEIO DE PUBLICAÇÃO",
      "DATA DO TRÂNSITO EM JULGADO",
      "ABRAGÊNCIA DA SANÇÃO",
      "ÓRGÃO SANCIONADOR",
      "UF ÓRGÃO SANCIONADOR",
      "ESFERA ÓRGÃO SANCIONADOR",
      "FUNDAMENTAÇÃO LEGAL",
      "DATA ORIGEM INFORMAÇÃO",
      "ORIGEM INFORMAÇÕES",
      "OBSERVAÇÕES"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CPF OU CNPJ DO SANCIONADO",
      "NOME DO SANCIONADO",
      "NOME INFORMADO PELO ÓRGÃO SANCIONADOR",
      "RAZÃO SOCIAL - CADASTRO RECEITA",
      "NOME FANTASIA - CADASTRO RECEITA",
      "NÚMERO DO PROCESSO",
      "ÓRGÃO SANCIONADOR",
      "UF ÓRGÃO SANCIONADOR",
      "ESFERA ÓRGÃO SANCIONADOR"
    ],
    "dateColumns": [
      "DATA INÍCIO SANÇÃO",
      "DATA FINAL SANÇÃO",
      "DATA PUBLICAÇÃO",
      "DATA DO TRÂNSITO EM JULGADO",
      "DATA ORIGEM INFORMAÇÃO"
    ],
    "valueColumns": [],
    "hasAudit": true
  },
  "_cepim": {
    "table": "_cepim",
    "columns": [
      "CNPJ ENTIDADE",
      "NOME ENTIDADE",
      "NÚMERO CONVÊNIO",
      "ÓRGÃO CONCEDENTE",
      "MOTIVO DO IMPEDIMENTO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CNPJ ENTIDADE",
      "NOME ENTIDADE",
      "ÓRGÃO CONCEDENTE"
    ],
    "dateColumns": [],
    "valueColumns": [],
    "hasAudit": true
  },
  "_cnep": {
    "table": "_cnep",
    "columns": [
      "CADASTRO",
      "CÓDIGO DA SANÇÃO",
      "TIPO DE PESSOA",
      "CPF OU CNPJ DO SANCIONADO",
      "NOME DO SANCIONADO",
      "NOME INFORMADO PELO ÓRGÃO SANCIONADOR",
      "RAZÃO SOCIAL - CADASTRO RECEITA",
      "NOME FANTASIA - CADASTRO RECEITA",
      "NÚMERO DO PROCESSO",
      "CATEGORIA DA SANÇÃO",
      "VALOR DA MULTA",
      "DATA INÍCIO SANÇÃO",
      "DATA FINAL SANÇÃO",
      "DATA PUBLICAÇÃO",
      "PUBLICAÇÃO",
      "DETALHAMENTO DO MEIO DE PUBLICAÇÃO",
      "DATA DO TRÂNSITO EM JULGADO",
      "ABRAGÊNCIA DA SANÇÃO",
      "ÓRGÃO SANCIONADOR",
      "UF ÓRGÃO SANCIONADOR",
      "ESFERA ÓRGÃO SANCIONADOR",
      "FUNDAMENTAÇÃO LEGAL",
      "DATA ORIGEM INFORMAÇÃO",
      "ORIGEM INFORMAÇÕES",
      "OBSERVAÇÕES"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CPF OU CNPJ DO SANCIONADO",
      "NOME DO SANCIONADO",
      "NOME INFORMADO PELO ÓRGÃO SANCIONADOR",
      "RAZÃO SOCIAL - CADASTRO RECEITA",
      "NOME FANTASIA - CADASTRO RECEITA",
      "NÚMERO DO PROCESSO",
      "ÓRGÃO SANCIONADOR",
      "UF ÓRGÃO SANCIONADOR",
      "ESFERA ÓRGÃO SANCIONADOR"
    ],
    "dateColumns": [
      "DATA INÍCIO SANÇÃO",
      "DATA FINAL SANÇÃO",
      "DATA PUBLICAÇÃO",
      "DATA DO TRÂNSITO EM JULGADO",
      "DATA ORIGEM INFORMAÇÃO"
    ],
    "valueColumns": [
      "VALOR DA MULTA"
    ],
    "hasAudit": true
  },
  "_compras": {
    "table": "_compras",
    "columns": [
      "Número Contrato",
      "Código Órgão Superior",
      "Nome Órgão Superior",
      "Código Órgão",
      "Nome Órgão",
      "Código UG",
      "Nome UG",
      "Número Apostilamento",
      "Descrição Apostilamento",
      "Valor Apostilamento",
      "Data de inclusão",
      "Situação Apostilamento",
      "Número do Contrato",
      "Objeto",
      "Fundamento Legal",
      "Modalidade Compra",
      "Situação Contrato",
      "Data Assinatura Contrato",
      "Data Publicação DOU",
      "Data Início Vigência",
      "Data Fim Vigência",
      "Código Contratado",
      "Nome Contratado",
      "Valor Inicial Compra",
      "Valor Final Compra",
      "Número Licitação",
      "Código UG Licitação",
      "Nome UG Licitação",
      "Código Modalidade Compra Licitação",
      "Modalidade Compra Licitação",
      "Código Item Compra",
      "Descrição Item Compra",
      "Descrição Complementar Item Compra",
      "Quantidade Item",
      "Valor Item",
      "Número Termo Aditivo",
      "Data Publicação"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "Código Órgão Superior",
      "Nome Órgão Superior",
      "Código Órgão",
      "Nome Órgão",
      "Nome UG",
      "Nome Contratado",
      "Nome UG Licitação"
    ],
    "dateColumns": [
      "Data de inclusão",
      "Data Assinatura Contrato",
      "Data Publicação DOU",
      "Data Início Vigência",
      "Data Fim Vigência",
      "Data Publicação"
    ],
    "valueColumns": [
      "Valor Apostilamento",
      "Valor Inicial Compra",
      "Valor Final Compra",
      "Quantidade Item",
      "Valor Item"
    ],
    "hasAudit": true
  },
  "_convenios": {
    "table": "_convenios",
    "columns": [
      "NÚMERO CONVÊNIO",
      "NÚMERO ORIGINAL",
      "DATA EMISSÃO OB",
      "NÚMERO DA ORDEM BANCÁRIA",
      "VALOR LIBERADO",
      "UF",
      "CÓDIGO SIAFI MUNICÍPIO",
      "NOME MUNICÍPIO",
      "SITUAÇÃO CONVÊNIO",
      "NÚMERO PROCESSO DO CONVÊNIO",
      "OBJETO DO CONVÊNIO",
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO CONCEDENTE",
      "NOME ÓRGÃO CONCEDENTE",
      "CÓDIGO UG CONCEDENTE",
      "NOME UG CONCEDENTE",
      "CÓDIGO CONVENENTE",
      "TIPO CONVENENTE",
      "NOME CONVENENTE",
      "TIPO ENTE CONVENENTE",
      "TIPO INSTRUMENTO",
      "VALOR CONVÊNIO",
      "DATA PUBLICAÇÃO",
      "DATA INÍCIO VIGÊNCIA",
      "DATA FINAL VIGÊNCIA",
      "VALOR CONTRAPARTIDA",
      "DATA ÚLTIMA LIBERAÇÃO",
      "VALOR ÚLTIMA LIBERAÇÃO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO SIAFI MUNICÍPIO",
      "NOME MUNICÍPIO",
      "NÚMERO PROCESSO DO CONVÊNIO",
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO CONCEDENTE",
      "NOME ÓRGÃO CONCEDENTE",
      "NOME UG CONCEDENTE",
      "NOME CONVENENTE"
    ],
    "dateColumns": [
      "DATA EMISSÃO OB",
      "DATA PUBLICAÇÃO",
      "DATA INÍCIO VIGÊNCIA",
      "DATA FINAL VIGÊNCIA",
      "DATA ÚLTIMA LIBERAÇÃO"
    ],
    "valueColumns": [
      "VALOR LIBERADO",
      "VALOR CONVÊNIO",
      "VALOR CONTRAPARTIDA",
      "VALOR ÚLTIMA LIBERAÇÃO"
    ],
    "hasAudit": true
  },
  "_cpcc": {
    "table": "_cpcc",
    "columns": [
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO",
      "NOME ÓRGÃO",
      "CÓDIGO UNIDADE GESTORA",
      "NOME UNIDADE GESTORA",
      "ANO EXTRATO",
      "MÊS EXTRATO",
      "TIPO AQUISIÇÃO",
      "CNPJ OU CPF FAVORECIDO",
      "NOME FAVORECIDO",
      "TRANSAÇÃO",
      "DATA TRANSAÇÃO",
      "VALOR TRANSAÇÃO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO",
      "NOME ÓRGÃO",
      "NOME UNIDADE GESTORA",
      "CNPJ OU CPF FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "ANO EXTRATO",
      "MÊS EXTRATO",
      "DATA TRANSAÇÃO"
    ],
    "valueColumns": [
      "VALOR TRANSAÇÃO"
    ],
    "hasAudit": true
  },
  "_cpdc": {
    "table": "_cpdc",
    "columns": [
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO",
      "NOME ÓRGÃO",
      "CÓDIGO UNIDADE GESTORA",
      "NOME UNIDADE GESTORA",
      "ANO EXTRATO",
      "MÊS EXTRATO",
      "CPF PORTADOR",
      "NOME PORTADOR",
      "CNPJ OU CPF FAVORECIDO",
      "NOME FAVORECIDO",
      "EXECUTOR DESPESA",
      "NÚMERO CONVÊNIO",
      "CÓDIGO CONVENENTE",
      "NOME CONVENENTE",
      "REPASSE",
      "TRANSAÇÃO",
      "DATA TRANSAÇÃO",
      "VALOR TRANSAÇÃO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO",
      "NOME ÓRGÃO",
      "NOME UNIDADE GESTORA",
      "CPF PORTADOR",
      "NOME PORTADOR",
      "CNPJ OU CPF FAVORECIDO",
      "NOME FAVORECIDO",
      "NOME CONVENENTE"
    ],
    "dateColumns": [
      "ANO EXTRATO",
      "MÊS EXTRATO",
      "DATA TRANSAÇÃO"
    ],
    "valueColumns": [
      "VALOR TRANSAÇÃO"
    ],
    "hasAudit": true
  },
  "_cpgf": {
    "table": "_cpgf",
    "columns": [
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO",
      "NOME ÓRGÃO",
      "CÓDIGO UNIDADE GESTORA",
      "NOME UNIDADE GESTORA",
      "ANO EXTRATO",
      "MÊS EXTRATO",
      "CPF PORTADOR",
      "NOME PORTADOR",
      "CNPJ OU CPF FAVORECIDO",
      "NOME FAVORECIDO",
      "TRANSAÇÃO",
      "DATA TRANSAÇÃO",
      "VALOR TRANSAÇÃO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO",
      "NOME ÓRGÃO",
      "NOME UNIDADE GESTORA",
      "CPF PORTADOR",
      "NOME PORTADOR",
      "CNPJ OU CPF FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "ANO EXTRATO",
      "MÊS EXTRATO",
      "DATA TRANSAÇÃO"
    ],
    "valueColumns": [
      "VALOR TRANSAÇÃO"
    ],
    "hasAudit": true
  },
  "_despesas_favorecidos": {
    "table": "_despesas_favorecidos",
    "columns": [
      "Código Favorecido",
      "Nome Favorecido",
      "Sigla UF",
      "Nome Município",
      "Código Órgão Superior",
      "Nome Órgão Superior",
      "Código Órgão",
      "Nome Órgão",
      "Código Unidade Gestora",
      "Nome Unidade Gestora",
      "Ano e mês do lançamento",
      "Valor Recebido"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "Código Favorecido",
      "Nome Favorecido",
      "Nome Município",
      "Código Órgão Superior",
      "Nome Órgão Superior",
      "Código Órgão",
      "Nome Órgão",
      "Nome Unidade Gestora"
    ],
    "dateColumns": [
      "Ano e mês do lançamento"
    ],
    "valueColumns": [
      "Valor Recebido"
    ],
    "hasAudit": true
  },
  "_despesasdiarias": {
    "table": "_despesasdiarias",
    "columns": [
      "Id Empenho",
      "Código Empenho",
      "Código Empenho Resumido",
      "Data Emissão",
      "Código Tipo Documento",
      "Tipo Documento",
      "Tipo Empenho",
      "Espécie Empenho",
      "Código Órgão Superior",
      "Órgão Superior",
      "Código Órgão",
      "Órgão",
      "Código Unidade Gestora",
      "Unidade Gestora",
      "Código Gestão",
      "Gestão",
      "Código Favorecido",
      "Favorecido",
      "Observação",
      "Código Esfera Orçamentária",
      "Esfera Orçamentária",
      "Código Tipo Crédito",
      "Tipo Crédito",
      "Código Grupo Fonte Recurso",
      "Grupo Fonte Recurso",
      "Código Fonte Recurso",
      "Fonte Recurso",
      "Código Unidade Orçamentária",
      "Unidade Orçamentária",
      "Código Função",
      "Função",
      "Código SubFunção",
      "SubFunção",
      "Código Programa",
      "Programa",
      "Código Ação",
      "Ação",
      "Linguagem Cidadã",
      "Código Subtítulo (Localizador)",
      "Subtítulo (Localizador)",
      "Código Plano Orçamentário",
      "Plano Orçamentário",
      "Código Programa Governo",
      "Nome Programa Governo",
      "Autor Emenda",
      "Código Categoria de Despesa",
      "Categoria de Despesa",
      "Código Grupo de Despesa",
      "Grupo de Despesa",
      "Código Modalidade de Aplicação",
      "Modalidade de Aplicação",
      "Código Elemento de Despesa",
      "Elemento de Despesa",
      "Processo",
      "Modalidade de Licitação",
      "Inciso",
      "Amparo",
      "Referência de Dispensa ou Inexigibilidade",
      "Código Convênio",
      "Contrato de Repasse / Termo de Parceria / Outros",
      "Valor Original do Empenho",
      "Valor do Empenho Convertido pra R$",
      "Valor Utilizado na Conversão",
      "Código SubElemento de Despesa",
      "SubElemento de Despesa",
      "Descrição",
      "Quantidade",
      "Valor Unitário",
      "Valor Total",
      "Sequencial",
      "Valor Atual",
      "Código Liquidação",
      "Código Natureza Despesa Completa",
      "Subitem",
      "Valor Liquidado (R$)",
      "Valor Restos a Pagar Inscritos (R$)",
      "Valor Restos a Pagar Cancelado (R$)",
      "Valor Restos a Pagar Pagos (R$)",
      "Código Liquidação Resumido",
      "Código Pagamento",
      "Valor Pago (R$)",
      "Código Lista",
      "Valor do Pagamento em R$",
      "Código Banco",
      "Nome Banco",
      "Agência",
      "Valor em R$",
      "Código Sequência",
      "Valor Lançamento em R$",
      "Valor Desconto em R$",
      "Valor Juros em R$",
      "Valor Dedução em R$",
      "Valor Acréscimo em R$",
      "Número Parcela",
      "Valor Precatorio em R$",
      "Código Pagamento Resumido",
      "Tipo OB",
      "Extraorçamentário",
      "Valor Original do Pagamento",
      "Valor do Pagamento Convertido pra R$",
      "Tipo Operação",
      "Data Operação",
      "Quantidade Item",
      "Valor Unitário Item",
      "Valor Total Item"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "Código Tipo Documento",
      "Tipo Documento",
      "Código Órgão Superior",
      "Órgão Superior",
      "Código Órgão",
      "Órgão",
      "Código Favorecido",
      "Favorecido",
      "Código Função",
      "Função",
      "Código SubFunção",
      "SubFunção",
      "Nome Programa Governo",
      "Processo",
      "Nome Banco"
    ],
    "dateColumns": [
      "Data Emissão",
      "Código Plano Orçamentário",
      "Plano Orçamentário",
      "Data Operação"
    ],
    "valueColumns": [
      "Valor Original do Empenho",
      "Valor do Empenho Convertido pra R$",
      "Valor Utilizado na Conversão",
      "Quantidade",
      "Valor Unitário",
      "Valor Total",
      "Valor Atual",
      "Valor Liquidado (R$)",
      "Valor Restos a Pagar Inscritos (R$)",
      "Valor Restos a Pagar Cancelado (R$)",
      "Valor Restos a Pagar Pagos (R$)",
      "Valor Pago (R$)",
      "Valor do Pagamento em R$",
      "Valor em R$",
      "Valor Lançamento em R$",
      "Valor Desconto em R$",
      "Valor Juros em R$",
      "Valor Dedução em R$",
      "Valor Acréscimo em R$",
      "Valor Precatorio em R$",
      "Valor Original do Pagamento",
      "Valor do Pagamento Convertido pra R$",
      "Quantidade Item",
      "Valor Unitário Item",
      "Valor Total Item"
    ],
    "hasAudit": true
  },
  "_emendas": {
    "table": "_emendas",
    "columns": [
      "Código da Emenda",
      "Código Função",
      "Nome Função",
      "Código Subfunção",
      "Nome Subfunção",
      "Localidade do gasto",
      "Tipo de Emenda",
      "Data Publicação Convênio",
      "Convenente",
      "Objeto Convênio",
      "Número Convênio",
      "Valor Convênio",
      "Código do Autor da Emenda",
      "Nome do Autor da Emenda",
      "Número da emenda",
      "Ano/Mês",
      "Código do Favorecido",
      "Favorecido",
      "Natureza Jurídica",
      "Tipo Favorecido",
      "UF Favorecido",
      "Município Favorecido",
      "Valor Recebido",
      "Ano da Emenda",
      "Localidade de aplicação do recurso",
      "Código Município IBGE",
      "Município",
      "Código UF IBGE",
      "UF",
      "Região",
      "Código Programa",
      "Nome Programa",
      "Código Ação",
      "Nome Ação",
      "Código Plano Orçamentário",
      "Nome Plano Orçamentário",
      "Valor Empenhado",
      "Valor Liquidado",
      "Valor Pago",
      "Valor Restos A Pagar Inscritos",
      "Valor Restos A Pagar Cancelados",
      "Valor Restos A Pagar Pagos"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "Código Função",
      "Nome Função",
      "Código Subfunção",
      "Nome Subfunção",
      "Nome do Autor da Emenda",
      "Código do Favorecido",
      "Favorecido",
      "Tipo Favorecido",
      "UF Favorecido",
      "Município Favorecido",
      "Código Município IBGE",
      "Município",
      "Nome Programa",
      "Nome Ação",
      "Nome Plano Orçamentário"
    ],
    "dateColumns": [
      "Data Publicação Convênio",
      "Ano/Mês",
      "Ano da Emenda",
      "Código Plano Orçamentário",
      "Nome Plano Orçamentário"
    ],
    "valueColumns": [
      "Valor Convênio",
      "Valor Recebido",
      "Valor Empenhado",
      "Valor Liquidado",
      "Valor Pago",
      "Valor Restos A Pagar Inscritos",
      "Valor Restos A Pagar Cancelados",
      "Valor Restos A Pagar Pagos"
    ],
    "hasAudit": true
  },
  "_emendasparlamentarespordocumento": {
    "table": "_emendasparlamentarespordocumento",
    "columns": [
      "Código da Emenda",
      "Ano da Emenda",
      "Código do Autor da Emenda",
      "Nome do Autor da Emenda",
      "Número da emenda",
      "Valor Empenhado",
      "Valor Pago",
      "Tipo de Emenda",
      "Data Documento",
      "Código Documento",
      "Localidade de aplicação do recurso",
      "UF de aplicação do recurso",
      "Município de aplicação do recurso",
      "Código IBGE do município de aplicação do recurso",
      "Fase da despesa",
      "Código favorecido",
      "Favorecido",
      "Tipo Favorecido",
      "UF Favorecido",
      "Município Favorecido",
      "Código UG",
      "UG",
      "Código Unidade Orçamentária",
      "Unidade Orçamentária",
      "Código Órgão SIAFI",
      "Órgão",
      "Código Órgão Superior SIAFI",
      "Órgão Superior",
      "Código Grupo Despesa",
      "Grupo Despesa",
      "Código Elemento Despesa",
      "Elemento Despesa",
      "Código Modalidade Aplicação Despesa",
      "Modalidade Aplicação Despesa",
      "Código Plano Orçamentário",
      "Plano Orçamentário",
      "Código Função",
      "Função",
      "Código SubFunção",
      "SubFunção",
      "Código Programa",
      "Programa",
      "Código Ação",
      "Ação",
      "Linguagem Cidadã",
      "Código Subtítulo (Localizador)",
      "Subtítulo (Localizador)",
      "Possui convênio?"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "Nome do Autor da Emenda",
      "Data Documento",
      "Código Documento",
      "Município de aplicação do recurso",
      "Código IBGE do município de aplicação do recurso",
      "Código favorecido",
      "Favorecido",
      "Tipo Favorecido",
      "UF Favorecido",
      "Município Favorecido",
      "Código Órgão SIAFI",
      "Órgão",
      "Código Órgão Superior SIAFI",
      "Órgão Superior",
      "Código Função",
      "Função",
      "Código SubFunção",
      "SubFunção"
    ],
    "dateColumns": [
      "Ano da Emenda",
      "Data Documento",
      "Código Plano Orçamentário",
      "Plano Orçamentário"
    ],
    "valueColumns": [
      "Valor Empenhado",
      "Valor Pago"
    ],
    "hasAudit": true
  },
  "_execucaodareceita": {
    "table": "_execucaodareceita",
    "columns": [
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO",
      "NOME ÓRGÃO",
      "CÓDIGO UNIDADE GESTORA",
      "NOME UNIDADE GESTORA",
      "CATEGORIA ECONÔMICA",
      "ORIGEM RECEITA",
      "ESPÉCIE RECEITA",
      "DETALHAMENTO",
      "VALOR PREVISTO ATUALIZADO",
      "VALOR LANÇADO",
      "VALOR REALIZADO",
      "PERCENTUAL REALIZADO",
      "DATA LANÇAMENTO",
      "ANO EXERCÍCIO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO",
      "NOME ÓRGÃO",
      "NOME UNIDADE GESTORA"
    ],
    "dateColumns": [
      "DATA LANÇAMENTO",
      "ANO EXERCÍCIO"
    ],
    "valueColumns": [
      "VALOR PREVISTO ATUALIZADO",
      "VALOR LANÇADO",
      "VALOR REALIZADO"
    ],
    "hasAudit": true
  },
  "_favorecidospj": {
    "table": "_favorecidospj",
    "columns": [
      "COD_SECAO",
      "DESC_SECAO",
      "COD_SUBCLASSE",
      "DESC_SUBCLASSE",
      "CNPJ",
      "RAZAOSOCIAL",
      "NOMEFANTASIA",
      "COD_CNAE",
      "COD_NATJURIDICA",
      "TIPO_PESSOA",
      "LOGRADOURO",
      "NUMERO",
      "COMPLEMENTO",
      "CEP",
      "BAIRRO",
      "MUNICIPIO",
      "UF",
      "DESC_NATJURIDICA",
      "COD_TIPO_NATJURIDICA",
      "DESC_TIPO_NATJURIDICA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CNPJ",
      "NOMEFANTASIA",
      "MUNICIPIO"
    ],
    "dateColumns": [],
    "valueColumns": [],
    "hasAudit": true
  },
  "_garantiasafra": {
    "table": "_garantiasafra",
    "columns": [
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "MÊS REFERÊNCIA"
    ],
    "valueColumns": [
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_imoveisfuncionais": {
    "table": "_imoveisfuncionais",
    "columns": [
      "Endereço",
      "Órgão Responsável",
      "Situação",
      "Nome Permissionário",
      "CPF",
      "Cargo ou Função",
      "Órgão Exercício",
      "Data de Ocupação",
      "ENDEREÇO",
      "ÓRGÃO RESPONSÁVEL",
      "SITUAÇÃO",
      "NOME PERMISSIONÁRIO",
      "CARGO OU FUNÇÃO DE CONFIANÇA",
      "ÓRGÃO EXERCÍCIO DO PERMISSIONÁRIO",
      "DATA INÍCIO OCUPAÇÃO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "Órgão Responsável",
      "Nome Permissionário",
      "CPF",
      "Cargo ou Função",
      "Órgão Exercício",
      "ÓRGÃO RESPONSÁVEL",
      "NOME PERMISSIONÁRIO",
      "CARGO OU FUNÇÃO DE CONFIANÇA",
      "ÓRGÃO EXERCÍCIO DO PERMISSIONÁRIO"
    ],
    "dateColumns": [
      "Data de Ocupação",
      "DATA INÍCIO OCUPAÇÃO"
    ],
    "valueColumns": [],
    "hasAudit": true
  },
  "_licitacoes": {
    "table": "_licitacoes",
    "columns": [
      "Número Licitação",
      "Código UG",
      "Nome UG",
      "Código Modalidade Compra",
      "Modalidade Compra",
      "Número Processo",
      "Código Empenho",
      "Data Emissão Empenho",
      "Observação Empenho",
      "Valor Empenho (R$)",
      "Código Órgão",
      "Nome Órgão",
      "Código Item Compra",
      "Descrição",
      "Quantidade Item",
      "Valor Item",
      "Código Vencedor",
      "Nome Vencedor",
      "Objeto",
      "Situação Licitação",
      "Código Órgão Superior",
      "Nome Órgão Superior",
      "UF",
      "Município",
      "Data Resultado Compra",
      "Data Abertura",
      "Valor Licitação",
      "Descrição Item Compra",
      "Código Participante",
      "Nome Participante",
      "Flag Vencedor"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "Nome UG",
      "Número Processo",
      "Código Órgão",
      "Nome Órgão",
      "Nome Vencedor",
      "Código Órgão Superior",
      "Nome Órgão Superior",
      "Município",
      "Nome Participante"
    ],
    "dateColumns": [
      "Data Emissão Empenho",
      "Data Resultado Compra",
      "Data Abertura"
    ],
    "valueColumns": [
      "Valor Empenho (R$)",
      "Quantidade Item",
      "Valor Item",
      "Valor Licitação"
    ],
    "hasAudit": true
  },
  "_notasfiscais": {
    "table": "_notasfiscais",
    "columns": [
      "CHAVE DE ACESSO",
      "MODELO",
      "SÉRIE",
      "NÚMERO",
      "NATUREZA DA OPERAÇÃO",
      "DATA EMISSÃO",
      "EVENTO",
      "DATA/HORA EVENTO",
      "DESCRIÇÃO EVENTO",
      "MOTIVO EVENTO",
      "CPF/CNPJ Emitente",
      "RAZÃO SOCIAL EMITENTE",
      "INSCRIÇÃO ESTADUAL EMITENTE",
      "UF EMITENTE",
      "MUNICÍPIO EMITENTE",
      "CÓDIGO ÓRGÃO SUPERIOR DESTINATÁRIO",
      "ÓRGÃO SUPERIOR DESTINATÁRIO",
      "CÓDIGO ÓRGÃO DESTINATÁRIO",
      "ÓRGÃO DESTINATÁRIO",
      "CNPJ DESTINATÁRIO",
      "NOME DESTINATÁRIO",
      "UF DESTINATÁRIO",
      "INDICADOR IE DESTINATÁRIO",
      "DESTINO DA OPERAÇÃO",
      "CONSUMIDOR FINAL",
      "PRESENÇA DO COMPRADOR",
      "NÚMERO PRODUTO",
      "DESCRIÇÃO DO PRODUTO/SERVIÇO",
      "CÓDIGO NCM/SH",
      "NCM/SH (TIPO DE PRODUTO)",
      "CFOP",
      "QUANTIDADE",
      "UNIDADE",
      "VALOR UNITÁRIO",
      "VALOR TOTAL",
      "EVENTO MAIS RECENTE",
      "DATA/HORA EVENTO MAIS RECENTE",
      "VALOR NOTA FISCAL"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CPF/CNPJ Emitente",
      "RAZÃO SOCIAL EMITENTE",
      "MUNICÍPIO EMITENTE",
      "CÓDIGO ÓRGÃO SUPERIOR DESTINATÁRIO",
      "ÓRGÃO SUPERIOR DESTINATÁRIO",
      "CÓDIGO ÓRGÃO DESTINATÁRIO",
      "ÓRGÃO DESTINATÁRIO",
      "CNPJ DESTINATÁRIO",
      "NOME DESTINATÁRIO"
    ],
    "dateColumns": [
      "DATA EMISSÃO",
      "DATA/HORA EVENTO",
      "DATA/HORA EVENTO MAIS RECENTE"
    ],
    "valueColumns": [
      "QUANTIDADE",
      "VALOR UNITÁRIO",
      "VALOR TOTAL",
      "VALOR NOTA FISCAL"
    ],
    "hasAudit": true
  },
  "_novobolsafamilia": {
    "table": "_novobolsafamilia",
    "columns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "MÊS COMPETÊNCIA",
      "MÊS REFERÊNCIA"
    ],
    "valueColumns": [
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_orcamentodadespesa": {
    "table": "_orcamentodadespesa",
    "columns": [
      "EXERCÍCIO",
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO SUBORDINADO",
      "NOME ÓRGÃO SUBORDINADO",
      "CÓDIGO UNIDADE ORÇAMENTÁRIA",
      "NOME UNIDADE ORÇAMENTÁRIA",
      "CÓDIGO FUNÇÃO",
      "NOME FUNÇÃO",
      "CÓDIGO SUBFUNÇÃO",
      "NOME SUBFUNÇÃO",
      "CÓDIGO PROGRAMA ORÇAMENTÁRIO",
      "NOME PROGRAMA ORÇAMENTÁRIO",
      "CÓDIGO AÇÃO",
      "NOME AÇÃO",
      "CÓDIGO CATEGORIA ECONÔMICA",
      "NOME CATEGORIA ECONÔMICA",
      "CÓDIGO GRUPO DE DESPESA",
      "NOME GRUPO DE DESPESA",
      "CÓDIGO ELEMENTO DE DESPESA",
      "NOME ELEMENTO DE DESPESA",
      "ORÇAMENTO INICIAL (R$)",
      "ORÇAMENTO ATUALIZADO (R$)",
      "ORÇAMENTO EMPENHADO (R$)",
      "ORÇAMENTO REALIZADO (R$)",
      "% REALIZADO DO ORÇAMENTO (COM RELAÇÃO AO ORÇAMENTO ATUALIZADO)"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO ÓRGÃO SUPERIOR",
      "NOME ÓRGÃO SUPERIOR",
      "CÓDIGO ÓRGÃO SUBORDINADO",
      "NOME ÓRGÃO SUBORDINADO",
      "NOME UNIDADE ORÇAMENTÁRIA",
      "CÓDIGO FUNÇÃO",
      "NOME FUNÇÃO",
      "CÓDIGO SUBFUNÇÃO",
      "NOME SUBFUNÇÃO",
      "NOME PROGRAMA ORÇAMENTÁRIO",
      "NOME AÇÃO",
      "NOME CATEGORIA ECONÔMICA",
      "NOME GRUPO DE DESPESA",
      "NOME ELEMENTO DE DESPESA"
    ],
    "dateColumns": [],
    "valueColumns": [],
    "hasAudit": true
  },
  "_pedemeia": {
    "table": "_pedemeia",
    "columns": [
      "MÊS FOLHA",
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "NIS BENEFICIÁRIO",
      "CPF BENEFICIÁRIO",
      "NOME BENEFICIÁRIO",
      "NIS RESPONSÁVEL",
      "CPF RESPONSÁVEL",
      "NOME RESPONSÁVEL",
      "CÓDIGO ETAPA ENSINO",
      "ETAPA ENSINO",
      "CÓDIGO TIPO INCENTIVO",
      "TIPO INCENTIVO",
      "DATA DO PAGAMENTO",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF BENEFICIÁRIO",
      "NOME BENEFICIÁRIO",
      "CPF RESPONSÁVEL",
      "NOME RESPONSÁVEL"
    ],
    "dateColumns": [
      "MÊS FOLHA",
      "MÊS REFERÊNCIA",
      "DATA DO PAGAMENTO"
    ],
    "valueColumns": [
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_pep": {
    "table": "_pep",
    "columns": [
      "CPF",
      "Nome_PEP",
      "Sigla_Função",
      "Descrição_Função",
      "Nível_Função",
      "Nome_Órgão",
      "Data_Início_Exercício",
      "Data_Fim_Exercício",
      "Data_Fim_Carência"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CPF",
      "Nome_PEP",
      "Sigla_Função",
      "Descrição_Função",
      "Nível_Função",
      "Nome_Órgão"
    ],
    "dateColumns": [
      "Data_Início_Exercício",
      "Data_Fim_Exercício",
      "Data_Fim_Carência"
    ],
    "valueColumns": [],
    "hasAudit": true
  },
  "_peti": {
    "table": "_peti",
    "columns": [
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO SIAFI MUNICÍPIO",
      "NOME MUNICÍPIO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO",
      "SITUAÇÃO BENEFÍCIO",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO SIAFI MUNICÍPIO",
      "NOME MUNICÍPIO",
      "NIS FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "MÊS REFERÊNCIA"
    ],
    "valueColumns": [
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_renunciasfiscais": {
    "table": "_renunciasfiscais",
    "columns": [
      "CNPJ",
      "Razão Social",
      "Nome Fantasia",
      "Código CNAE",
      "CNAE",
      "Município",
      "UF",
      "Benefício Fiscal",
      "Base Legal",
      "Descrição",
      "Início Habilitação",
      "Fim Habilitação",
      "Ano-calendário",
      "Tipo Entidade",
      "Valor Renúncia Fiscal (R$)",
      "Tipo Renúncia",
      "Fundamento Legal",
      "Tributo",
      "Forma Tributação"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CNPJ",
      "Razão Social",
      "Nome Fantasia",
      "Município"
    ],
    "dateColumns": [
      "Ano-calendário"
    ],
    "valueColumns": [
      "Valor Renúncia Fiscal (R$)"
    ],
    "hasAudit": true
  },
  "_rfb_empresas": {
    "table": "_rfb_empresas",
    "columns": [
      "cnpj_basico",
      "razao_social",
      "natureza_juridica_codigo",
      "natureza_juridica",
      "qualificacao_responsavel_codigo",
      "qualificacao_responsavel",
      "capital_social",
      "porte_codigo",
      "porte",
      "ente_federativo"
    ],
    "auditColumns": [],
    "searchColumns": [],
    "dateColumns": [],
    "valueColumns": [],
    "hasAudit": false
  },
  "_rfb_estabelecimentos": {
    "table": "_rfb_estabelecimentos",
    "columns": [
      "bairro",
      "cep",
      "cidade_exterior",
      "cnae_principal",
      "cnae_principal_codigo",
      "cnaes_secundarios_codigos",
      "cnaes_secundarios_descricoes",
      "cnpj_basico",
      "cnpj_completo",
      "cnpj_dv",
      "cnpj_ordem",
      "complemento",
      "correio_eletronico",
      "data_inicio_atividade",
      "data_situacao_cadastral",
      "data_situacao_especial",
      "ddd_1",
      "ddd_2",
      "ddd_fax",
      "fax",
      "logradouro",
      "matriz_filial",
      "matriz_filial_codigo",
      "motivo_situacao",
      "motivo_situacao_codigo",
      "municipio",
      "municipio_codigo",
      "nome_fantasia",
      "numero",
      "pais",
      "pais_codigo",
      "situacao_cadastral",
      "situacao_cadastral_codigo",
      "situacao_especial",
      "telefone_1",
      "telefone_2",
      "tipo_logradouro",
      "uf"
    ],
    "auditColumns": [],
    "searchColumns": [
      "municipio",
      "municipio_codigo",
      "nome_fantasia"
    ],
    "dateColumns": [
      "data_inicio_atividade",
      "data_situacao_cadastral",
      "data_situacao_especial"
    ],
    "valueColumns": [],
    "hasAudit": false
  },
  "_rfb_simples": {
    "table": "_rfb_simples",
    "columns": [
      "cnpj_basico",
      "data_exclusao_mei",
      "data_exclusao_simples",
      "data_opcao_mei",
      "data_opcao_simples",
      "opcao_mei",
      "opcao_mei_codigo",
      "opcao_simples",
      "opcao_simples_codigo"
    ],
    "auditColumns": [],
    "searchColumns": [],
    "dateColumns": [
      "data_exclusao_mei",
      "data_exclusao_simples",
      "data_opcao_mei",
      "data_opcao_simples"
    ],
    "valueColumns": [],
    "hasAudit": false
  },
  "_rfb_socios": {
    "table": "_rfb_socios",
    "columns": [
      "cnpj_basico",
      "cpf_cnpj_socio",
      "data_entrada_sociedade",
      "faixa_etaria",
      "faixa_etaria_codigo",
      "identificador_socio",
      "identificador_socio_codigo",
      "nome_representante",
      "nome_socio",
      "pais",
      "pais_codigo",
      "qualificacao_representante_legal",
      "qualificacao_representante_legal_codigo",
      "qualificacao_socio",
      "qualificacao_socio_codigo",
      "representante_legal"
    ],
    "auditColumns": [],
    "searchColumns": [
      "nome_representante",
      "nome_socio"
    ],
    "dateColumns": [
      "data_entrada_sociedade"
    ],
    "valueColumns": [],
    "hasAudit": false
  },
  "_segurodefeso": {
    "table": "_segurodefeso",
    "columns": [
      "MÊS REFERÊNCIA",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "RGP FAVORECIDO",
      "NOME FAVORECIDO",
      "VALOR PARCELA"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CPF FAVORECIDO",
      "NIS FAVORECIDO",
      "RGP FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "MÊS REFERÊNCIA"
    ],
    "valueColumns": [
      "VALOR PARCELA"
    ],
    "hasAudit": true
  },
  "_servidores": {
    "table": "_servidores",
    "columns": [
      "ANO",
      "MES",
      "Id_SERVIDOR_PORTAL",
      "CPF",
      "NOME",
      "EMPRESA",
      "VALOR",
      "MATRICULA",
      "DESCRICAO_CARGO",
      "CLASSE_CARGO",
      "REFERENCIA_CARGO",
      "PADRAO_CARGO",
      "NIVEL_CARGO",
      "SIGLA_FUNCAO",
      "NIVEL_FUNCAO",
      "FUNCAO",
      "CODIGO_ATIVIDADE",
      "ATIVIDADE",
      "OPCAO_PARCIAL",
      "COD_UORG_LOTACAO",
      "UORG_LOTACAO",
      "COD_ORG_LOTACAO",
      "ORG_LOTACAO",
      "COD_ORGSUP_LOTACAO",
      "ORGSUP_LOTACAO",
      "COD_UORG_EXERCICIO",
      "UORG_EXERCICIO",
      "COD_ORG_EXERCICIO",
      "ORG_EXERCICIO",
      "COD_ORGSUP_EXERCICIO",
      "ORGSUP_EXERCICIO",
      "COD_TIPO_VINCULO",
      "TIPO_VINCULO",
      "SITUACAO_VINCULO",
      "DATA_INICIO_AFASTAMENTO",
      "DATA_TERMINO_AFASTAMENTO",
      "REGIME_JURIDICO",
      "JORNADA_DE_TRABALHO",
      "DATA_INGRESSO_CARGOFUNCAO",
      "DATA_NOMEACAO_CARGOFUNCAO",
      "DATA_INGRESSO_ORGAO",
      "DOCUMENTO_INGRESSO_SERVICOPUBLICO",
      "DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO",
      "DIPLOMA_INGRESSO_CARGOFUNCAO",
      "DIPLOMA_INGRESSO_ORGAO",
      "DIPLOMA_INGRESSO_SERVICOPUBLICO",
      "UF_EXERCICIO",
      "OBSERVACAO",
      "REMUNERAÇÃO BÁSICA BRUTA (R$)",
      "REMUNERAÇÃO BÁSICA BRUTA (U$)",
      "ABATE-TETO (R$)",
      "ABATE-TETO (U$)",
      "GRATIFICAÇÃO NATALINA (R$)",
      "GRATIFICAÇÃO NATALINA (U$)",
      "ABATE-TETO DA GRATIFICAÇÃO NATALINA (R$)",
      "ABATE-TETO DA GRATIFICAÇÃO NATALINA (U$)",
      "FÉRIAS (R$)",
      "FÉRIAS (U$)",
      "OUTRAS REMUNERAÇÕES EVENTUAIS (R$)",
      "OUTRAS REMUNERAÇÕES EVENTUAIS (U$)",
      "IRRF (R$)",
      "IRRF (U$)",
      "PSS/RPGS (R$)",
      "PSS/RPGS (U$)",
      "DEMAIS DEDUÇÕES (R$)",
      "DEMAIS DEDUÇÕES (U$)",
      "PENSÃO MILITAR (R$)",
      "PENSÃO MILITAR (U$)",
      "FUNDO DE SAÚDE (R$)",
      "FUNDO DE SAÚDE (U$)",
      "TAXA DE OCUPAÇÃO IMÓVEL FUNCIONAL (R$)",
      "TAXA DE OCUPAÇÃO IMÓVEL FUNCIONAL (U$)",
      "REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (R$)",
      "REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (U$)",
      "VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (R$)(*)",
      "VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - CIVIL (U$)(*)",
      "VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (R$)(*)",
      "VERBAS INDENIZATÓRIAS REGISTRADAS EM SISTEMAS DE PESSOAL - MILITAR (U$)(*)",
      "VERBAS INDENIZATÓRIAS PROGRAMA DESLIGAMENTO VOLUNTÁRIO – MP 792/2017 (R$)",
      "VERBAS INDENIZATÓRIAS PROGRAMA DESLIGAMENTO VOLUNTÁRIO – MP 792/2017 (U$)",
      "TOTAL DE VERBAS INDENIZATÓRIAS (R$)(*)",
      "TOTAL DE VERBAS INDENIZATÓRIAS (U$)(*)",
      "DATA_FIM_AFASTAMENTO",
      "OBSERVACOES",
      "COD_TIPO_APOSENTADORIA",
      "TIPO_APOSENTADORIA",
      "DATA_APOSENTADORIA",
      "CPF_REPRESENTANTE_LEGAL",
      "NOME_REPRESENTANTE_LEGAL",
      "CPF_INSTITUIDOR_PENSAO",
      "NOME_INSTITUIDOR_PENSAO",
      "COD_TIPO_PENSAO",
      "TIPO_PENSAO",
      "DATA_INICIO_PENSAO",
      "DESCRICAO_CARGO_INSTITUIDOR_PENSAO",
      "COD_UORG_LOTACAO_INSTITUIDOR_PENSAO",
      "UORG_LOTACAO_INSTITUIDOR_PENSAO",
      "COD_ORG_LOTACAO_INSTITUIDOR_PENSAO",
      "ORG_LOTACAO_INSTITUIDOR_PENSAO",
      "COD_ORGSUP_LOTACAO_INSTITUIDOR_PENSAO",
      "ORGSUP_LOTACAO_INSTITUIDOR_PENSAO",
      "REGIME_JURIDICO_INSTITUIDOR_PENSAO",
      "JORNADA_DE_TRABALHO_INSTITUIDOR_PENSAO",
      "DATA_INGRESSO_CARGOFUNCAO_INSTITUIDOR_PENSAO",
      "DATA_NOMEACAO_CARGOFUNCAO_INSTITUIDOR_PENSAO",
      "DATA_INGRESSO_ORGAO_INSTITUIDOR_PENSAO",
      "DOCUMENTO_INGRESSO_SERVICOPUBLICO_INSTITUIDOR_PENSAO",
      "DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO_INSTITUIDOR_PENSAO",
      "DIPLOMA_INGRESSO_CARGOFUNCAO_INSTITUIDOR_PENSAO",
      "DIPLOMA_INGRESSO_ORGAO_INSTITUIDOR_PENSAO",
      "DIPLOMA_INGRESSO_SERVICOPUBLICO_INSTITUIDOR_PENSAO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "CPF",
      "NOME",
      "DESCRICAO_CARGO",
      "CLASSE_CARGO",
      "REFERENCIA_CARGO",
      "PADRAO_CARGO",
      "NIVEL_CARGO",
      "SIGLA_FUNCAO",
      "NIVEL_FUNCAO",
      "FUNCAO",
      "DATA_INGRESSO_CARGOFUNCAO",
      "DATA_NOMEACAO_CARGOFUNCAO",
      "DATA_INGRESSO_ORGAO",
      "DOCUMENTO_INGRESSO_SERVICOPUBLICO",
      "DIPLOMA_INGRESSO_CARGOFUNCAO",
      "DIPLOMA_INGRESSO_ORGAO",
      "NOME_REPRESENTANTE_LEGAL",
      "NOME_INSTITUIDOR_PENSAO",
      "DESCRICAO_CARGO_INSTITUIDOR_PENSAO",
      "DATA_INGRESSO_CARGOFUNCAO_INSTITUIDOR_PENSAO",
      "DATA_NOMEACAO_CARGOFUNCAO_INSTITUIDOR_PENSAO",
      "DATA_INGRESSO_ORGAO_INSTITUIDOR_PENSAO",
      "DOCUMENTO_INGRESSO_SERVICOPUBLICO_INSTITUIDOR_PENSAO",
      "DIPLOMA_INGRESSO_CARGOFUNCAO_INSTITUIDOR_PENSAO",
      "DIPLOMA_INGRESSO_ORGAO_INSTITUIDOR_PENSAO"
    ],
    "dateColumns": [
      "ANO",
      "MES",
      "DATA_INICIO_AFASTAMENTO",
      "DATA_TERMINO_AFASTAMENTO",
      "DATA_INGRESSO_CARGOFUNCAO",
      "DATA_NOMEACAO_CARGOFUNCAO",
      "DATA_INGRESSO_ORGAO",
      "DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO",
      "DATA_FIM_AFASTAMENTO",
      "DATA_APOSENTADORIA",
      "DATA_INICIO_PENSAO",
      "DATA_INGRESSO_CARGOFUNCAO_INSTITUIDOR_PENSAO",
      "DATA_NOMEACAO_CARGOFUNCAO_INSTITUIDOR_PENSAO",
      "DATA_INGRESSO_ORGAO_INSTITUIDOR_PENSAO",
      "DATA_DIPLOMA_INGRESSO_SERVICOPUBLICO_INSTITUIDOR_PENSAO"
    ],
    "valueColumns": [
      "VALOR",
      "REMUNERAÇÃO BÁSICA BRUTA (R$)",
      "REMUNERAÇÃO BÁSICA BRUTA (U$)",
      "REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (R$)",
      "REMUNERAÇÃO APÓS DEDUÇÕES OBRIGATÓRIAS (U$)",
      "TOTAL DE VERBAS INDENIZATÓRIAS (R$)(*)",
      "TOTAL DE VERBAS INDENIZATÓRIAS (U$)(*)"
    ],
    "hasAudit": true
  },
  "_transferencias": {
    "table": "_transferencias",
    "columns": [
      "ANO / MÊS",
      "TIPO TRANSFERÊNCIA",
      "TIPO FAVORECIDO",
      "UF",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CÓDIGO ÓRGÃO SIAFI",
      "NOME ÓRGÃO",
      "CÓDIGO UNIDADE GESTORA",
      "NOME UNIDADE GESTORA",
      "CÓDIGO FUNÇÃO",
      "NOME FUNÇÃO",
      "CÓDIGO SUBFUNÇÃO",
      "NOME SUBFUNÇÃO",
      "CÓDIGO PROGRAMA",
      "NOME PROGRAMA",
      "AÇÃO",
      "NOME AÇÃO",
      "LINGUAGEM CIDADÃ",
      "CÓDIGO GRUPO DESPESA",
      "NOME GRUPO DESPESA",
      "CÓDIGO MODALIDADE APLICAÇÃO DESPESA",
      "NOME MODALIDADE APLICAÇÃO DESPESA",
      "CÓDIGO ELEMENTO DESPESA",
      "NOME ELEMENTO DESPESA",
      "CÓDIGO PLANO ORÇAMENTÁRIO",
      "NOME PLANO ORÇAMENTÁRIO",
      "CÓDIGO SUBTÍTULO",
      "NOME SUBTÍTULO",
      "CÓDIGO LOCALIZADOR",
      "NOME LOCALIZADOR",
      "SIGLA LOCALIZADOR",
      "DESCRIÇÃO COMPLEMENTAR LOCALIZADOR",
      "CÓDIGO FAVORECIDO",
      "NOME FAVORECIDO",
      "VALOR TRANSFERIDO"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "TIPO FAVORECIDO",
      "CÓDIGO MUNICÍPIO SIAFI",
      "NOME MUNICÍPIO",
      "CÓDIGO ÓRGÃO SIAFI",
      "NOME ÓRGÃO",
      "NOME UNIDADE GESTORA",
      "CÓDIGO FUNÇÃO",
      "NOME FUNÇÃO",
      "CÓDIGO SUBFUNÇÃO",
      "NOME SUBFUNÇÃO",
      "NOME PROGRAMA",
      "NOME AÇÃO",
      "NOME GRUPO DESPESA",
      "NOME MODALIDADE APLICAÇÃO DESPESA",
      "NOME ELEMENTO DESPESA",
      "NOME PLANO ORÇAMENTÁRIO",
      "NOME SUBTÍTULO",
      "NOME LOCALIZADOR",
      "CÓDIGO FAVORECIDO",
      "NOME FAVORECIDO"
    ],
    "dateColumns": [
      "ANO / MÊS",
      "CÓDIGO PLANO ORÇAMENTÁRIO",
      "NOME PLANO ORÇAMENTÁRIO"
    ],
    "valueColumns": [
      "VALOR TRANSFERIDO"
    ],
    "hasAudit": true
  },
  "_viagens": {
    "table": "_viagens",
    "columns": [
      "Identificador do processo de viagem",
      "Número da Proposta (PCDP)",
      "Código do órgão superior",
      "Nome do órgão superior",
      "Codigo do órgão pagador",
      "Nome do órgao pagador",
      "Código da unidade gestora pagadora",
      "Nome da unidade gestora pagadora",
      "Tipo de pagamento",
      "Valor",
      "Meio de transporte",
      "País - Origem ida",
      "UF - Origem ida",
      "Cidade - Origem ida",
      "País - Destino ida",
      "UF - Destino ida",
      "Cidade - Destino ida",
      "País - Origem volta",
      "UF - Origem volta",
      "Cidade - Origem volta",
      "Pais - Destino volta",
      "UF - Destino volta",
      "Cidade - Destino volta",
      "Valor da passagem",
      "Taxa de serviço",
      "Data da emissão/compra",
      "Hora da emissão/compra",
      "Sequência Trecho",
      "Origem - Data",
      "Origem - País",
      "Origem - UF",
      "Origem - Cidade",
      "Destino - Data",
      "Destino - País",
      "Destino - UF",
      "Destino - Cidade",
      "Número Diárias",
      "Missao?",
      "Situação",
      "Viagem Urgente",
      "Justificativa Urgência Viagem",
      "Código órgão solicitante",
      "Nome órgão solicitante",
      "CPF viajante",
      "Nome",
      "Cargo",
      "Função",
      "Descrição Função",
      "Período - Data de início",
      "Período - Data de fim",
      "Destinos",
      "Motivo",
      "Valor diárias",
      "Valor passagens",
      "Valor devolução",
      "Valor outros gastos"
    ],
    "auditColumns": [
      "_audit_url_download",
      "_audit_data_disponibilizacao_gov",
      "_audit_periodicidade",
      "_audit_data_processamento",
      "_audit_arquivo_csv_origem",
      "_audit_linha_csv",
      "_audit_row_hash"
    ],
    "searchColumns": [
      "Identificador do processo de viagem",
      "Código do órgão superior",
      "Nome do órgão superior",
      "Codigo do órgão pagador",
      "Nome do órgao pagador",
      "Nome da unidade gestora pagadora",
      "Código órgão solicitante",
      "Nome órgão solicitante",
      "CPF viajante",
      "Nome",
      "Cargo",
      "Função",
      "Descrição Função"
    ],
    "dateColumns": [
      "Data da emissão/compra",
      "Origem - Data",
      "Destino - Data",
      "Período - Data de início",
      "Período - Data de fim"
    ],
    "valueColumns": [
      "Valor",
      "Valor da passagem",
      "Valor diárias",
      "Valor passagens",
      "Valor devolução",
      "Valor outros gastos"
    ],
    "hasAudit": true
  }
};
